spring:
  cloud:
    discovery:
      enabled: true
  r2dbc:
    url: r2dbc:pool:postgresql://transaction-service-db:5432/transactions
    username: postgres
    password: password
  flyway:
    url: jdbc:postgresql://transaction-service-db:5432/transactions
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
    locations: 'classpath:db/migration'
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

---

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8081/auth/realms/moneymaker
      client:
        registration:
          transaction-service:
            provider: keycloak
            client-id: transaction-service
            client-secret: je8fIE6iHlkU6Qv53PaBrFrlcrp7tHak
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://keycloak:8081/auth/realms/moneymaker

---

spring:
  rabbitmq:
    username: test
    password: test
    host: mm-mq
    port: 5672

---

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
    org.springframework.r2dbc: DEBUG
debug: true
