spring:
  cloud:
    discovery:
      enabled: true
    loadbalancer:
      enabled: true
  r2dbc:
    url: r2dbc:h2:mem:///~/db/testdb
    username: sa
    password:
  flyway:
    url: jdbc:h2:mem:~/db/testdb;DB_CLOSE_DELAY=-1
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
    locations: 'classpath:db/migration,test_data'
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
server:
  port: 8082
ribbon:
  eureka:
    enabled: true