spring:
  cloud:
    discovery:
      enabled: true
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/transaction
    username: keycloak
    password: password
  flyway:
    url: jdbc:mysql://localhost:3306/transaction
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
server:
  port: 8082


---

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/moneymaker
      client:
        registration:
          oaka-transaction-service:
            provider: keycloak
            client-id: oaka-transaction-service
            client-secret: fe9eb8a0-d930-4c9e-8d62-b1932835ad6a
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/auth/realms/moneymaker

