spring:
  cloud:
    discovery:
      enabled: true
  r2dbc:
    url: r2dbc:h2:mem:DATABASE;MODE=MYSQL
    username: sa
    password:
  flyway:
    url: jdbc:h2:mem://172.16.0.7:3306/mm_transaction_dev
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
debug: false
server:
  port: 8082