spring:
  codec:
    max-in-memory-size: 10MB
  cloud:
    kubernetes:
      enabled: false
      discovery:
        enabled: false
    discovery:
      enabled: false
  flyway:
    enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters