spring:
  cloud:
    discovery:
      enabled: true
    loadbalancer:
      enabled: true
  r2dbc:
    url: r2dbc:h2:mem:///~/db/testdb
    username: sa
    password:
  flyway:
    url: jdbc:h2:mem:~/db/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    locations: 'classpath:db/migration,test_data'
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: 8082
ribbon:
  eureka:
    enabled: true

---

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/moneymaker
      client:
        registration:
          transaction-service:
            provider: keycloak
            client-id: transaction-service
            client-secret: fe9eb8a0-d930-4c9e-8d62-b1932835ad6a
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/auth/realms/moneymaker

---

spring:
  rabbitmq:
    username: test
    password: test