spring:
  cloud:
    discovery:
      enabled: true
  r2dbc:
    url: r2dbc:h2:mem:///~/db/testdb
    username: sa
    password:
  flyway:
    url: jdbc:h2:mem:~/db/testdb;DB_CLOSE_DELAY=-1
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
    locations: 'classpath:db/migration,test_data'
eureka:
  client:
    serviceUrl:
      defaultZone: http://mm-eureka:8761/eureka/