spring:
  cloud:
    discovery:
      enabled: true
  r2dbc:
    url: r2dbc:pool:mysql://172.16.0.7:3306/mm_transaction_dev
    username: app_user
    password: 6NSMqvSszpKq42Jf
  flyway:
    url: jdbc:mysql://172.16.0.7:3306/mm_transaction_dev
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
server:
  port: 8082