version: 2.1

workflows:
  my-workflow:
    jobs:
      - build-and-test:
          context:
            - docker-login
          filters:
            branches:
              only:
                - main

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-maven-debs-{{ checksum "pom.xml" }}
            - v1-maven-debs
      - run:
          name: Test
          command: |
            chmod +x ./mvnw
            ./mvnw clean test
      - run:
          name: Package
          command: ./mvnw clean package -DskipTests
      - save_cache:
          key: v1-maven-debs-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export IMAGE_NAME=mm-oaka-transaction-service' >> $BASH_ENV
            echo 'export DOCKER_REPOSITORY=repo.treescale.com/jaydamon' >> $BASH_ENV
      - run:
          name: setup semantic-release
          command: |
            npm set prefix=/home/circleci/npm && echo 'export PATH=$HOME/circleci/npm/bin:$PATH' >> /home/circleci/.bashrc
            npm install -g semantic-release @semantic-release/{git,changelog,exec} semantic-release-plus @semantic-release-plus/docker
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Prepare Release
          command: |
            chmod +x ./prepare-release.sh
            /home/circleci/npm/bin/semantic-release
      - run:
          name: Build and Push Image
          command: |
            echo 'export VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')' $BASH_ENV
            echo 'export MAJOR_VERSION=$(git describe --tags --abbrev=0 | cut -f1 -d"." | sed 's/v//')' $BASH_ENV
            echo 'export MINOR_VERSION=$(git describe --tags --abbrev=0 | cut -f1-2 -d"." | sed 's/v//')' $BASH_ENV
            echo git describe --tags --abbrev=0 | sed 's/v//'
            echo $VERSION
            echo $MAJOR_VERSION
            echo $MINOR_VERSION
            docker build -t $DOCKER_REPOSITORY/$IMAGE_NAME:$VERSION -t $DOCKER_REPOSITORY/$IMAGE_NAME:MAJOR_VERSION -t $DOCKER_REPOSITORY/$IMAGE_NAME:MINOR_VERSION -t $DOCKER_REPOSITORY/$IMAGE_NAME:latest .
            docker push
