version: 2.1

workflows:
  my-workflow:
    jobs:
      - build-and-test:
          context:
            - docker-login
          filters:
            branches:
              only:
                - main

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-maven-debs-{{ checksum "pom.xml" }}
            - v1-maven-debs
      - run:
          name: Test
          command: |
            chmod +x ./mvnw
            ./mvnw clean test
      - run:
          name: Package
          command: ./mvnw clean package -DskipTests
      - save_cache:
          key: v1-maven-debs-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export IMAGE_NAME=mm-oaka-transaction-service' >> $BASH_ENV
            echo 'export DOCKER_REPOSITORY=repo.treescale.com/jaydamon' >> $BASH_ENV
      - run:
          name: setup semantic-release
          command: |
            npm set prefix=/home/circleci/npm && echo 'export PATH=$HOME/circleci/npm/bin:$PATH' >> /home/circleci/.bashrc
            npm install -g semantic-release @semantic-release/{git,changelog,exec} semantic-release-plus @semantic-release-plus/docker
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build and push Docker image
          command: |
            docker build -t $DOCKER_REPOSITORY/$IMAGE_NAME .
            chmod +x ./prepare-release.sh
            /home/circleci/npm/bin/semantic-release